#ifndef _MATH_EXP_H
#define _MATH_EXP_H

typedef enum math_exp_type {
	MATH_BRACKET_START,
	MATH_BRACKET_END,
	MATH_LESS_THAN_EQ,
	MATH_LESS_THAN,
	MATH_GREATER_THAN,
    MATH_GREATER_THAN_EQ,
	MATH_EQ,
	MATH_NOT_EQ,
	MATH_AND,
	MATH_OR,
	MATH_MUL,
	MATH_PLUS,
	MATH_MINUS,
	MATH_DIV,
	MATH_COMMA,
	MATH_SQRT,
	MATH_SQR,
	MATH_MAX,
	MATH_MIN,
	MATH_SIN,
	MATH_COS,
	MATH_POW,
	MATH_INTEGER_VALUE,
	MATH_DOUBLE_VALUE,
	MATH_IDENTIFIER,
	MATH_IDENTIFIER_IDENTIFIER,
	MATH_STRING_VALUE,
	MATH_SPACE,

	MATH_EXP_MAX,
} math_exp_type;

typedef enum extra_enum {
	PARSER_EOL = (int) MATH_EXP_MAX + 1,
	PARSER_QUIT,
} extra_enum;


#endif
